In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
iris=load_iris()


log=LogisticRegression(max_iter=500)
log.fit(iris.data, iris.target)
classes=log.predict(iris.data)

probs=log.predict_proba(iris.data)

from sklearn.metrics import classification_report

classification_report(iris.target,classes,labels=[0,1])

from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

f1_score(iris.target,classes,average=None),recall_score(iris.target,classes,average=None),precision_score(iris.target,classes,average=None),\
f1_score(iris.target,classes,average='micro'),recall_score(iris.target,classes,average='micro'),precision_score(iris.target,classes,average='micro'),





(array([1.        , 0.95918367, 0.96078431]),
 array([1.  , 0.94, 0.98]),
 array([1.        , 0.97916667, 0.94230769]),
 0.9733333333333334,
 0.9733333333333334,
 0.9733333333333334)

In [9]:
from sklearn.multiclass import OneVsRestClassifier
ovr=OneVsRestClassifier(LogisticRegression())
ovr.fit(iris.data,iris.target)
classes=ovr.predict(iris.data)
probs=ovr.predict_proba(iris.data)
probs.sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
from sklearn.preprocessing import LabelBinarizer

bin=LabelBinarizer()
bin.fit([0,1,2,])
target_2d=bin.transform(iris.target)

ovr=OneVsRestClassifier(LogisticRegression())
ovr.fit(iris.data,target_2d)
classes=ovr.predict(iris.data)
probs=ovr.predict_proba(iris.data)
probs[0],probs.sum(axis=1)[0]

(array([9.84064852e-01, 1.13231638e-01, 1.17651820e-06]), 1.0972976662997165)

In [35]:
from sklearn.multioutput import MultiOutputClassifier
#from sklearn.datasets import make_multilabel_classification

#Just using previous 2d output 
target_2d[1:4]=[2,2,2]
moc=MultiOutputClassifier(LogisticRegression(max_iter=500))
moc.fit(iris.data,target_2d)
classes=moc.predict(iris.data)
probs=moc.predict_proba(iris.data)
for prob in probs:
    print(prob.shape,prob.sum(axis=1))

(150, 3) [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]
(150, 3) [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]
(150, 3) [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

In [39]:
from sklearn.model_selection import train_test_split
a,b,c,d=train_test_split(iris.data,iris.target,test_size=0.3)
a.shape,c.shape, b.shape,d.shape

((105, 4), (105,), (45, 4), (45,))

In [43]:
import numpy as np
np.percentile(iris.data[:,1],q=95)
import pandas as pd
df=pd.DataFrame(iris.data)
df.quantile(0.9)

0    6.90
1    3.61
2    5.80
3    2.20
Name: 0.9, dtype: float64

In [63]:
import nltk
nltk.download(['punkt','wordnet'])
from nltk.tokenize import word_tokenize
words=word_tokenize('sentence to split.full stops   afre covered;nevertheless')

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

cv=CountVectorizer( tokenizer=word_tokenize)
tokens=cv.fit_transform(['first sentence',' second sentence'])
print(tokens.toarray())
tfidf=TfidfTransformer()
tokens=tfidf.fit_transform(tokens)
tokens.toarray()


[[1 0 1]
 [0 1 1]]


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\advitha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\advitha\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


array([[0.81480247, 0.        , 0.57973867],
       [0.        , 0.81480247, 0.57973867]])